import { prisma, withTenant } from '../config/database';
import { calculatePricing } from './pricing';

/**
 * Runs the night audit for a specific tenant and date.
 * Wraps all queries in withTenant() to enforce RLS.
 */
export async function runNightAudit(tenantId: string, auditDate: Date) {
  return withTenant(tenantId, async () => {
    try {
      const targetDateStr = auditDate.toISOString().split('T')[0];

      // Ensure we don't double-run
      const existingLog = await (prisma as any).nightAuditLog.findFirst({
        where: { tenantId, auditDate }
      });

      if (existingLog && existingLog.status === 'success') {
        return { success: false, message: `Night audit already completed for ${targetDateStr}` };
      }

      let processedCount = 0;
      let totalRevenuePosted = 0;

      // Find all bookings that are currently 'checked_in'
      const activeBookings = await (prisma.booking as any).findMany({
        where: {
          tenantId,
          status: 'checked_in',
          checkInDate: { lte: auditDate },
          checkedOutAt: null
        },
        include: {
          bookingRooms: { include: { roomType: true, room: true } },
          bookingGuests: { select: { guestState: true }, take: 1 }
        }
      });

      // Pre-load existing folio charges for all bookings in one query to avoid N+1
      const bookingIds = activeBookings.map((b: any) => b.id);
      const existingCharges = await prisma.folioCharge.findMany({
        where: {
          bookingId: { in: bookingIds },
          category: 'room',
          isAutoGenerated: true,
          chargeDate: auditDate
        },
        select: { bookingId: true, description: true }
      });
      const chargedBookingDescriptions = new Set(existingCharges.map(c => `${c.bookingId}::${c.description}`));

      // Fetch tenant config for GST intra/inter-state logic
      const tenant = await prisma.tenant.findUnique({
        where: { id: tenantId },
        select: { state: true, config: true }
      });
      const propertyState = tenant?.state || '';

      for (const booking of activeBookings) {
        for (const br of booking.bookingRooms) {
          if (!br.roomTypeId) continue;
          
          const nextDay = new Date(auditDate);
          nextDay.setDate(nextDay.getDate() + 1);

          const pricing = await calculatePricing(
            tenantId,
            br.roomTypeId,
            auditDate,
            nextDay,
            booking.numAdults > 2 ? booking.numAdults - 2 : 0
          );

          const descriptionMatch = `Room charge - ${auditDate.toLocaleDateString('en-IN', { timeZone: 'Asia/Kolkata' })}`;
          const cacheKey = `${booking.id}::${descriptionMatch}`;

          if (!chargedBookingDescriptions.has(cacheKey)) {
            const subtotal = pricing.totalAmount;
            
            // Determine CGST+SGST vs IGST based on guest state vs property state
            const guestState = booking.bookingGuests?.[0]?.guestState || '';
            const isInterState = !!(guestState && propertyState && guestState.toLowerCase().trim() !== propertyState.toLowerCase().trim());
            
            const cgst = isInterState ? 0 : pricing.totalGst / 2;
            const sgst = isInterState ? 0 : pricing.totalGst / 2;
            const igst = isInterState ? pricing.totalGst : 0;
            
            await prisma.folioCharge.create({
              data: {
                tenantId,
                bookingId: booking.id,
                description: descriptionMatch,
                sacCode: '996311',
                quantity: 1,
                unitPrice: subtotal,
                totalPrice: subtotal,
                cgst,
                sgst,
                igst,
                chargeDate: auditDate,
                category: 'room',
                isAutoGenerated: true
              }
            });

            processedCount++;
            totalRevenuePosted += subtotal;
            chargedBookingDescriptions.add(cacheKey);
          }
        }
      }

      // Record the audit log
      await (prisma as any).nightAuditLog.create({
        data: {
          tenantId,
          auditDate,
          status: 'success',
          metrics: {
            processedBookings: activeBookings.length,
            folioChargesPosted: processedCount,
            totalRevenueAppended: totalRevenuePosted
          } as any
        }
      });

      return { success: true, processedCount, totalRevenuePosted };

    } catch (err) {
      console.error('[NIGHT AUDIT ERROR]', err);
      await (prisma as any).nightAuditLog.create({
        data: {
          tenantId,
          auditDate,
          status: 'failed',
          metrics: { error: (err as Error).message } as any
        }
      });
      throw err;
    }
  });
}
