import { prisma, withTenant } from '../config/database';
import { calculatePricing } from './pricing';

/**
 * Runs the night audit for a specific tenant and date.
 * Wraps all queries in withTenant() to enforce RLS.
 */
export async function runNightAudit(tenantId: string, auditDate: Date) {
  return withTenant(tenantId, async () => {
    try {
      const targetDateStr = auditDate.toISOString().split('T')[0];

      // Ensure we don't double-run
      const existingLog = await (prisma as any).nightAuditLog.findFirst({
        where: { tenantId, auditDate }
      });

      if (existingLog && existingLog.status === 'success') {
        return { success: false, message: `Night audit already completed for ${targetDateStr}` };
      }

      let processedCount = 0;
      let totalRevenuePosted = 0;

      // Find all bookings that are currently 'checked_in'
      const activeBookings = await (prisma.booking as any).findMany({
        where: {
          tenantId,
          status: 'checked_in',
          checkInDate: { lte: auditDate },
          checkedOutAt: null
        },
        include: {
          bookingRooms: { include: { roomType: true, room: true } },
          bookingGuests: { select: { guestState: true }, take: 1 }
        }
      });

      // Pre-load existing folio charges for all bookings in one query to avoid N+1
      const bookingIds = activeBookings.map((b: any) => b.id);
      const existingCharges = await prisma.folioCharge.findMany({
        where: {
          bookingId: { in: bookingIds },
          category: 'room',
          isAutoGenerated: true,
          chargeDate: auditDate
        },
        select: { bookingId: true, id: true }
      });
      
      // Group by booking ID to know how many rooms were already charged for this Date
      const chargesPerBooking = existingCharges.reduce((acc: any, c: any) => {
        acc[c.bookingId] = (acc[c.bookingId] || 0) + 1;
        return acc;
      }, {});

      // Fetch tenant config for GST intra/inter-state logic
      const tenant = await prisma.tenant.findUnique({
        where: { id: tenantId },
        select: { state: true, config: true }
      });
      const propertyState = tenant?.state || '';

      for (const booking of activeBookings) {
        let roomsChargedAlready = chargesPerBooking[booking.id] || 0;
        
        for (const br of booking.bookingRooms) {
          if (!br.roomTypeId) continue;

          // If we already have auto-generated room charges matching the number of rooms, skip!
          if (roomsChargedAlready >= booking.bookingRooms.length) {
            continue;
          }

          // Skip monthly-billed room types — their folio charges are created upfront, one per month
          const rt = await prisma.roomType.findUnique({ where: { id: br.roomTypeId }, select: { pricingUnit: true } });
          if (rt?.pricingUnit === 'monthly') continue;

          const nextDay = new Date(auditDate);
          nextDay.setDate(nextDay.getDate() + 1);

          const pricing = await calculatePricing(
            tenantId,
            br.roomTypeId,
            auditDate,
            nextDay,
            booking.numAdults > 2 ? booking.numAdults - 2 : 0
          );

          const descriptionMatch = `Room charge - ${auditDate.toLocaleDateString('en-IN', { timeZone: 'Asia/Kolkata' })}`;
          
          const subtotal = pricing.totalAmount;
          
          // Determine CGST+SGST vs IGST based on guest state vs property state
          const guestState = booking.bookingGuests?.[0]?.guestState || '';
          const isInterState = !!(guestState && propertyState && guestState.toLowerCase().trim() !== propertyState.toLowerCase().trim());
          
          const cgst = isInterState ? 0 : pricing.totalGst / 2;
          const sgst = isInterState ? 0 : pricing.totalGst / 2;
          const igst = isInterState ? pricing.totalGst : 0;
          
          await prisma.folioCharge.create({
            data: {
              tenantId,
              bookingId: booking.id,
              description: descriptionMatch,
              sacCode: '996311',
              quantity: 1,
              unitPrice: subtotal,
              totalPrice: subtotal,
              cgst,
              sgst,
              igst,
              chargeDate: auditDate,
              category: 'room',
              isAutoGenerated: true
            }
          });

          processedCount++;
          totalRevenuePosted += subtotal;
          roomsChargedAlready++; // Increment so we don't overcharge
        }
      }

      // Record the audit log
      await (prisma as any).nightAuditLog.create({
        data: {
          tenantId,
          auditDate,
          status: 'success',
          metrics: {
            processedBookings: activeBookings.length,
            folioChargesPosted: processedCount,
            totalRevenueAppended: totalRevenuePosted
          } as any
        }
      });

      return { success: true, processedCount, totalRevenuePosted };

    } catch (err) {
      console.error('[NIGHT AUDIT ERROR]', err);
      await (prisma as any).nightAuditLog.create({
        data: {
          tenantId,
          auditDate,
          status: 'failed',
          metrics: { error: (err as Error).message } as any
        }
      });
      throw err;
    }
  });
}

export async function getNightAuditSummary(tenantId: string, targetDateStr?: string) {
  return withTenant(tenantId, async () => {
    // 1. Determine date boundaries in IST
    const nowUtc = new Date();
    const currentIst = new Date(nowUtc.getTime() + (5.5 * 60 * 60 * 1000));
    const cy = currentIst.getUTCFullYear();
    const cm = String(currentIst.getUTCMonth() + 1).padStart(2, '0');
    const cd = String(currentIst.getUTCDate()).padStart(2, '0');
    const currentBusinessDateStr = `${cy}-${cm}-${cd}`;

    const dateStr = targetDateStr || currentBusinessDateStr;
    
    const targetDate = new Date(`${dateStr}T00:00:00Z`); // For @db.Date matching
    const startOfDayUtc = new Date(`${dateStr}T00:00:00+05:30`);
    const endOfDayUtc = new Date(startOfDayUtc.getTime() + 24 * 60 * 60 * 1000);

    // 2. Fetch Aggregations
    // Occupancy
    const rooms = await prisma.room.findMany({
      where: { tenantId, isActive: true },
      select: { status: true }
    });
    const occupancy = rooms.reduce((acc, r) => {
      if (r.status === 'occupied') acc.occupied++;
      else if (r.status === 'maintenance') acc.outOfOrder++;
      else acc.available++;
      return acc;
    }, { occupied: 0, available: 0, outOfOrder: 0, total: rooms.length });

    // Revenue
    const charges = await prisma.folioCharge.groupBy({
      by: ['category'],
      where: { tenantId, chargeDate: targetDate },
      _sum: { totalPrice: true }
    });
    const revenue = {
      room: charges.find((c: any) => c.category === 'room')?._sum.totalPrice || 0,
      fNb: charges.find((c: any) => c.category === 'f_and_b')?._sum.totalPrice || 0,
      other: charges.find((c: any) => !['room', 'f_and_b'].includes(c.category))?._sum.totalPrice || 0,
      total: charges.reduce((sum: number, c: any) => sum + (c._sum.totalPrice || 0), 0)
    };

    // Payments
    const payments = await prisma.guestPayment.groupBy({
      by: ['method'],
      where: { tenantId, createdAt: { gte: startOfDayUtc, lt: endOfDayUtc }, status: 'completed' },
      _sum: { amount: true }
    });
    const paymentsSummary = {
      cash: payments.find((p: any) => p.method.toLowerCase() === 'cash')?._sum.amount || 0,
      upi: payments.find((p: any) => p.method.toLowerCase() === 'upi')?._sum.amount || 0,
      card: payments.find((p: any) => p.method.toLowerCase() === 'card')?._sum.amount || 0,
      other: payments.find((p: any) => !['cash', 'upi', 'card'].includes(p.method.toLowerCase()))?._sum.amount || 0,
      total: payments.reduce((sum: number, p: any) => sum + (p._sum.amount || 0), 0)
    };

    // Alerts
    const noShows = await prisma.booking.findMany({
      where: {
        tenantId,
        status: 'confirmed',
        checkInDate: { lt: targetDate }
      },
      select: { id: true, bookingNumber: true, guestName: true, guestEmail: true }
    });

    const activeBookings = await prisma.booking.findMany({
      where: { tenantId, status: 'checked_in', checkedOutAt: null },
      select: { 
        id: true, 
        bookingNumber: true, 
        guestName: true,
        guestEmail: true,
        folioCharges: { select: { totalPrice: true } },
        guestPayments: { select: { amount: true } }
      }
    });

    const openFolios = activeBookings.filter((b: any) => {
      const totalCharged = b.folioCharges.reduce((s: number, c: any) => s + c.totalPrice, 0);
      const totalPaid = b.guestPayments.reduce((s: number, p: any) => s + p.amount, 0);
      return Math.round(totalCharged - totalPaid) > 0;
    }).map((b: any) => {
      const totalCharged = b.folioCharges.reduce((s: number, c: any) => s + c.totalPrice, 0);
      const totalPaid = b.guestPayments.reduce((s: number, p: any) => s + p.amount, 0);
      return {
        id: b.id,
        bookingNumber: b.bookingNumber,
        guestDetails: { name: b.guestName, email: b.guestEmail },
        balance: Math.round(totalCharged - totalPaid)
      };
    });

    // Check if Audit already run
    const existingLog = await (prisma as any).nightAuditLog.findFirst({
       where: { tenantId, auditDate: targetDate }
    });

    return {
      targetDateStr: dateStr,
      currentBusinessDateStr,
      auditStatus: existingLog ? existingLog.status : 'pending',
      occupancy,
      revenue,
      payments: paymentsSummary,
      alerts: { 
        noShows: noShows.map((ns: any) => ({ ...ns, guestDetails: { name: ns.guestName, email: ns.guestEmail } })),
        openFolios 
      }
    };
  });
}

export async function getNightAuditHistory(tenantId: string) {
  return withTenant(tenantId, async () => {
    return (prisma as any).nightAuditLog.findMany({
      where: { tenantId },
      orderBy: { auditDate: 'desc' },
      take: 30
    });
  });
}
