import { Router, Request, Response } from 'express';
import { prisma, withTenant, getLocalDate } from '../../config/database';
import { authenticate } from '../../middleware/auth';
import { resolveTenant, requireTenant } from '../../middleware/tenant-resolver';
import { authorize } from '../../middleware/rbac';
import { bookingSchema, bookingGuestSchema, walkInBookingSchema } from '@istays/shared';
import { logAudit } from '../../middleware/audit-log';
import { sendBookingConfirmation } from '../../services/email';
import { sendWhatsAppMessage } from '../../services/whatsapp';
import { calculatePricing } from '../../services/pricing';
import { pushInventoryUpdate } from '../../services/channel-manager';
import { creditLoyaltyPoints } from '../loyalty/router';

export const bookingsRouter = Router();

bookingsRouter.use(authenticate, resolveTenant, requireTenant);

// Generate unique booking number
function generateBookingNumber(): string {
  const prefix = 'IS';
  const timestamp = Date.now().toString(36).toUpperCase();
  const random = require('crypto').randomInt(1000, 9999).toString();
  return `${prefix}-${timestamp}-${random}`;
}

// Clamp pagination values for safety
function clampPagination(page: string | undefined, limit: string | undefined) {
  const p = Math.max(1, parseInt(page || '1', 10) || 1);
  const l = Math.min(100, Math.max(1, parseInt(limit || '20', 10) || 20));
  return { page: p, limit: l };
}

// POST /bookings
bookingsRouter.post('/', authorize('property_owner', 'general_manager', 'front_desk'), async (req: Request, res: Response) => {
  try {
    const parsed = bookingSchema.safeParse(req.body);
    if (!parsed.success) {
      res.status(400).json({ success: false, error: parsed.error.errors[0].message });
      return;
    }

    const data = parsed.data;

    const result = await withTenant(req.tenantId!, async () => {
      const bookingNumber = generateBookingNumber();

      // Calculate nights
      const nights = Math.ceil(
        (new Date(data.checkOutDate).getTime() - new Date(data.checkInDate).getTime()) / (1000 * 60 * 60 * 24),
      );

      if (nights <= 0) {
        return { error: 'Check-out must be after check-in', status: 400 };
      }

      // Calculate total from room selections
      let totalAmount = 0;
      const bookingRoomsData = [];
      const folioChargesData: any[] = [];

      const tenant = await prisma.tenant.findUnique({
        where: { id: req.tenantId! },
        select: { config: true, name: true },
      });
      const tenantConfig = (tenant?.config as Record<string, any>) || {};
      const propertyState = tenantConfig.state?.toLowerCase() || '';
      const guestState = data.guestState?.toLowerCase() || '';
      const isInterState = propertyState && guestState && propertyState !== guestState;

      for (const sel of data.roomSelections) {
        const pricing = await calculatePricing(
          req.tenantId!,
          sel.roomTypeId,
          new Date(data.checkInDate),
          new Date(data.checkOutDate),
          sel.extraBeds
        );

        totalAmount += pricing.grandTotal;
        
        // Wait till we get the first night's base rate for the legacy ratePerNight field, 
        // though typically we should save the nightly breakdn. For now, average it or use first night.
        const firstNightRate = pricing.nightlyRates.length > 0 ? pricing.nightlyRates[0].rate : 0;

        bookingRoomsData.push({
          tenantId: req.tenantId!,
          roomId: sel.roomId || null,
          roomTypeId: sel.roomTypeId,
          ratePerNight: firstNightRate, // Used for legacy displays
          extraBeds: sel.extraBeds,
          extraBedCharge: 0, // already included in calculatePricing
        });

        // Automatically generate FolioCharge records for exact taxation tracing
        for (const night of pricing.nightlyRates) {
          folioChargesData.push({
            tenantId: req.tenantId!,
            chargeDate: new Date(night.date),
            category: 'room',
            description: `Room charge - ${new Date(night.date).toLocaleDateString('en-IN', { timeZone: 'Asia/Kolkata' })} ${night.ruleApplied ? `(${night.ruleApplied})` : ''}`,
            sacCode: '996311',
            quantity: 1,
            unitPrice: night.rate,
            totalPrice: night.rate,
            gstRate: night.gstAmount > 0 && night.rate > 0 ? Math.round((night.gstAmount / night.rate) * 100) : 0,
            cgst: isInterState ? 0 : night.gstAmount / 2,
            sgst: isInterState ? 0 : night.gstAmount / 2,
            igst: isInterState ? night.gstAmount : 0,
            isAutoGenerated: true,
          });
        }
      }

      const advancePaid = data.advanceAmount || 0;
      const booking = await prisma.booking.create({
        data: {
          tenantId: req.tenantId!,
          bookingNumber,
          guestProfileId: data.guestProfileId || null,
          guestName: data.guestName,
          guestEmail: data.guestEmail?.toLowerCase() || null,
          guestPhone: data.guestPhone,
          source: data.source,
          checkInDate: new Date(data.checkInDate),
          checkOutDate: new Date(data.checkOutDate),
          numAdults: data.numAdults,
          numChildren: data.numChildren,
          numRooms: data.roomSelections.length,
          status: data.source === 'walkin' ? 'confirmed' : 'pending_confirmation',
          totalAmount,
          advancePaid,
          balanceDue: totalAmount - advancePaid,
          specialRequests: data.specialRequests || null,
          createdBy: req.userId,
          bookingRooms: { create: bookingRoomsData },
          bookingGuests: { create: [{ tenantId: req.tenantId!, fullName: data.guestName || 'Guest' }] },
          folioCharges: { create: folioChargesData },
        },
        include: { bookingRooms: true, folioCharges: true },
      });

      await logAudit(req.tenantId!, req.userId, 'CREATE', 'booking', booking.id, { bookingNumber, totalAmount }, req.ip || undefined);

      // Send confirmation email (async, don't await)
      if (data.guestEmail) {
        sendBookingConfirmation(data.guestEmail, {
          bookingNumber,
          guestName: data.guestName,
          propertyName: tenant?.name || 'Property',
          checkIn: data.checkInDate,
          checkOut: data.checkOutDate,
          totalAmount,
        }).catch(console.error);
      }

      // Send WhatsApp confirmation (async, don't await)
      if (data.guestPhone && tenantConfig.whatsapp?.enabled !== false) {
        sendWhatsAppMessage(
          data.guestPhone,
          {
            name: data.guestName,
            hotel: tenant?.name || 'Our Property',
            bookingRef: bookingNumber,
            checkInDate: new Date(data.checkInDate).toLocaleDateString('en-IN', { timeZone: 'Asia/Kolkata' })
          }
        ).catch(console.error);
      }

      // Async push inventory to OTAs
      const bookedRoomTypes = Object.fromEntries(
        data.roomSelections.map(r => [r.roomTypeId, true])
      );
      for (const roomTypeId of Object.keys(bookedRoomTypes)) {
        pushInventoryUpdate(req.tenantId!, roomTypeId, data.checkInDate, 0).catch(console.error);
      }

      return { data: booking };
    });

    if ('error' in result) {
      res.status(result.status || 400).json({ success: false, error: result.error });
      return;
    }

    res.status(201).json({ success: true, data: result.data, message: 'Booking created successfully' });

    // Async: Credit loyalty points (non-blocking)
    if (result.data?.guestProfileId && result.data?.totalAmount) {
      creditLoyaltyPoints(
        result.data.guestProfileId,
        req.tenantId!,
        result.data.id,
        result.data.totalAmount
      ).catch(console.error);
    }
  } catch (err) {
    console.error('[BOOKING CREATE ERROR]', err);
    res.status(500).json({ success: false, error: 'Failed to create booking' });
  }
});

// GET /bookings
bookingsRouter.get('/', async (req: Request, res: Response) => {
  try {
    const { status, startDate, endDate } = req.query;
    const { page, limit } = clampPagination(req.query.page as string, req.query.limit as string);

    await withTenant(req.tenantId!, async () => {
      const where: any = { tenantId: req.tenantId! };
      if (status) where.status = status;
      if (startDate) where.checkInDate = { ...(where.checkInDate || {}), gte: new Date(startDate as string) };
      if (endDate) where.checkOutDate = { ...(where.checkOutDate || {}), lte: new Date(endDate as string) };

      const [bookings, total] = await Promise.all([
        prisma.booking.findMany({
          where,
          include: {
            bookingRooms: {
              include: { room: { select: { roomNumber: true } }, roomType: { select: { name: true } } },
            },
          },
          orderBy: { createdAt: 'desc' },
          skip: (page - 1) * limit,
          take: limit,
        }),
        prisma.booking.count({ where }),
      ]);

      res.json({
        success: true,
        data: bookings,
        pagination: { page, limit, total, totalPages: Math.ceil(total / limit) },
      });
    });
  } catch (err) {
    console.error('[BOOKING LIST ERROR]', err);
    res.status(500).json({ success: false, error: 'Failed to fetch bookings' });
  }
});

// GET /bookings/:id
bookingsRouter.get('/:id', async (req: Request, res: Response) => {
  try {
    await withTenant(req.tenantId!, async () => {
      const booking = await prisma.booking.findUnique({
        where: { id: req.params.id },
        include: {
          bookingRooms: {
            include: {
              room: { select: { id: true, roomNumber: true, floor: { select: { name: true } } } },
              roomType: { select: { id: true, name: true } },
            },
          },
          bookingGuests: true,
          folioCharges: { orderBy: { chargeDate: 'asc' } },
          guestPayments: { orderBy: { createdAt: 'desc' } },
          invoices: true,
        },
      });

      if (!booking) {
        res.status(404).json({ success: false, error: 'Booking not found' });
        return;
      }

      res.json({ success: true, data: booking });
    });
  } catch (err) {
    console.error('[BOOKING GET ERROR]', err);
    res.status(500).json({ success: false, error: 'Failed to fetch booking' });
  }
});

// PUT /bookings/:id/guests/:guestId
bookingsRouter.post('/:id/guests', authorize('property_owner', 'general_manager', 'front_desk'), async (req: Request, res: Response) => { try { const result = await withTenant(req.tenantId!, async () => { const booking = await prisma.booking.findUnique({ where: { id: req.params.id } }); if (!booking) return { error: 'Booking not found', status: 404 }; const guest = await prisma.bookingGuest.create({ data: { tenantId: req.tenantId!, bookingId: booking.id, fullName: req.body.fullName || 'Unknown', nationality: req.body.nationality || 'Indian', idProofNumber: req.body.idProofNumber, visaNumber: req.body.visaNumber, visaExpiryDate: req.body.visaExpiryDate ? new Date(req.body.visaExpiryDate) : null, purposeOfVisit: req.body.purposeOfVisit, arrivingFrom: req.body.arrivingFrom, goingTo: req.body.goingTo } }); return { data: guest, status: 201 }; }); res.status(result.status || 200).json(result); } catch (err) { res.status(500).json({ error: 'Internal Error' }); } });

bookingsRouter.put('/:id/guests/:guestId', authorize('property_owner', 'general_manager', 'front_desk'), async (req: Request, res: Response) => {
  try {
    const result = await withTenant(req.tenantId!, async () => {
      const parsed = bookingGuestSchema.safeParse(req.body);
      if (!parsed.success) {
        return { error: 'Invalid guest data', status: 400, details: parsed.error.format() };
      }

      const existing = await prisma.bookingGuest.findUnique({ where: { id: req.params.guestId } });
      if (!existing || existing.bookingId !== req.params.id) return { error: 'Guest not found on this booking', status: 404 };

      const updated = await prisma.bookingGuest.update({
        where: { id: req.params.guestId },
        data: parsed.data
      });
      return { data: updated };
    });

    if ('error' in result) {
      res.status(result.status || 400).json({ success: false, error: result.error });
      return;
    }
    res.json({ success: true, data: result.data });
  } catch(err) {
    res.status(500).json({ success: false, error: 'Failed' });
  }
});

// PATCH /bookings/:id/confirm
bookingsRouter.patch('/:id/confirm', authorize('property_owner', 'general_manager', 'front_desk'), async (req: Request, res: Response) => {
  try {
    const result = await withTenant(req.tenantId!, async () => {
      // Verify booking exists and is in confirmable state
      const existing = await prisma.booking.findUnique({ where: { id: req.params.id }, select: { status: true } });
      if (!existing) return { error: 'Booking not found', status: 404 };
      if (existing.status !== 'pending_confirmation') {
        return { error: `Cannot confirm booking with status: ${existing.status}`, status: 400 };
      }

      const booking = await prisma.booking.update({
        where: { id: req.params.id },
        data: { status: 'confirmed' },
      });
      await logAudit(req.tenantId!, req.userId, 'CONFIRM', 'booking', booking.id, {}, req.ip || undefined);
      return { data: booking };
    });

    if ('error' in result) {
      res.status(result.status || 400).json({ success: false, error: result.error });
      return;
    }

    res.json({ success: true, data: result.data });
  } catch (err) {
    res.status(500).json({ success: false, error: 'Failed to confirm booking' });
  }
});

// POST /bookings/:id/cancel
bookingsRouter.post('/:id/cancel', authorize('property_owner', 'general_manager', 'front_desk'), async (req: Request, res: Response) => {
  try {
    const { reason } = req.body;

    const result = await withTenant(req.tenantId!, async () => {
      // Verify booking exists and is cancellable
      const existing = await prisma.booking.findUnique({ where: { id: req.params.id }, select: { status: true } });
      if (!existing) return { error: 'Booking not found', status: 404 };
      if (['checked_out', 'cancelled'].includes(existing.status)) {
        return { error: `Cannot cancel booking with status: ${existing.status}`, status: 400 };
      }

      const booking = await prisma.booking.update({
        where: { id: req.params.id },
        data: {
          status: 'cancelled',
          cancellationReason: reason || 'Cancelled by staff',
          cancelledAt: new Date(),
        },
      });

      // Release rooms
      const bookingRooms = await prisma.bookingRoom.findMany({ where: { bookingId: booking.id } });
      for (const br of bookingRooms) {
        if (br.roomId) {
          await prisma.room.update({ where: { id: br.roomId }, data: { status: 'available' } });
        }
      }

      await logAudit(req.tenantId!, req.userId, 'CANCEL', 'booking', booking.id, { reason }, req.ip || undefined);
      return { data: booking };
    });

    if ('error' in result) {
      res.status(result.status || 400).json({ success: false, error: result.error });
      return;
    }

    res.json({ success: true, data: result.data, message: 'Booking cancelled' });
  } catch (err) {
    res.status(500).json({ success: false, error: 'Failed to cancel booking' });
  }
});

// GET /bookings/:id/c-form
// Exports a CSV file for FRRO compliance (only includes Foreign guests)
bookingsRouter.get('/:id/c-form', async (req: Request, res: Response) => {
  try {
    await withTenant(req.tenantId!, async () => {
      const booking = await prisma.booking.findUnique({
        where: { id: req.params.id },
        include: {
          bookingGuests: true,
          tenant: { select: { name: true, city: true, address: true } }
        },
      });

      if (!booking) {
        res.status(404).json({ success: false, error: 'Booking not found' });
        return;
      }

      // Filter only non-Indian guests for C-Form
      const foreignGuests = booking.bookingGuests.filter(g => 
        g.nationality && g.nationality.toLowerCase() !== 'indian' && g.nationality.toLowerCase() !== 'india'
      );

      if (foreignGuests.length === 0) {
        res.status(400).json({ success: false, error: 'No foreign guests attached to this booking to generate a C-Form.' });
        return;
      }

      // FRRO standard CSV Headers
      const headers = [
        'Hotel Name', 'Booking Ref', 'Arrival Date', 'Guest Name', 'Nationality', 
        'Passport Number', 'Visa Number', 'Visa Expiry', 'Arriving From', 'Proceeding To', 'Purpose of Visit'
      ];

      const rows = foreignGuests.map(g => {
        return [
          `"${booking.tenant.name}"`,
          `"${booking.bookingNumber}"`,
          `"${new Date(booking.checkInDate).toISOString().split('T')[0]}"`,
          `"${g.fullName}"`,
          `"${g.nationality}"`,
          `"${g.idProofNumber || ''}"`,
          `"${g.visaNumber || ''}"`,
          `"${g.visaExpiryDate ? new Date(g.visaExpiryDate).toISOString().split('T')[0] : ''}"`,
          `"${g.arrivingFrom || ''}"`,
          `"${g.goingTo || ''}"`,
          `"${g.purposeOfVisit || ''}"`
        ].join(',');
      });

      const csvContent = [headers.join(','), ...rows].join('\n');

      res.setHeader('Content-Type', 'text/csv');
      res.setHeader('Content-Disposition', `attachment; filename=c-form-${booking.bookingNumber}.csv`);
      res.status(200).send(csvContent);
      
      // Update compliance flag in background
      await prisma.bookingGuest.updateMany({
        where: { id: { in: foreignGuests.map(fg => fg.id) } },
        data: { cFormSubmitted: true, cFormSubmittedAt: new Date() }
      });
    });
  } catch (err) {
    console.error('[C-FORM GENERATION ERROR]', err);
    res.status(500).json({ success: false, error: 'Failed to generate C-Form CSV' });
  }
});

// POST /bookings/walk-in
bookingsRouter.post('/walk-in', authorize('property_owner', 'general_manager', 'front_desk'), async (req: Request, res: Response) => {
  try {
    const parsed = walkInBookingSchema.safeParse(req.body);
    if (!parsed.success) {
      res.status(400).json({ success: false, error: parsed.error.errors[0].message });
      return;
    }

    const { guestName, guestPhone, roomId, durationValue, durationUnit, paymentMode } = parsed.data;

    const result = await withTenant(req.tenantId!, async () => {
      // 1. Validate room availability
      const room = await prisma.room.findUnique({
        where: { id: roomId, tenantId: req.tenantId! },
      });
      if (!room || room.status !== 'available') {
        return { error: 'Room is not available for walk-in', status: 400 };
      }

      // 2. Fetch or create guest profile
      let guestProfile = await prisma.guestProfile.findFirst({
        where: { phone: guestPhone, tenantId: req.tenantId! }
      });
      if (!guestProfile) {
        guestProfile = await prisma.guestProfile.create({
          data: {
            tenantId: req.tenantId!,
            fullName: guestName,
            phone: guestPhone,
          }
        });
      }

      // 3. Calculate Check-Out Date and Pricing
      // Use IST (Asia/Kolkata) for all date operations to avoid timezone drift
      const checkInDate = getLocalDate();
      const checkOutDate = new Date(checkInDate);
      
      if (durationUnit === 'days') {
        checkOutDate.setDate(checkOutDate.getDate() + durationValue);
      } else {
        checkOutDate.setMonth(checkOutDate.getMonth() + durationValue);
      }

      const pricing = await calculatePricing(
        req.tenantId!,
        room.roomTypeId,
        checkInDate,
        checkOutDate,
        0
      );

      const bookingNumber = generateBookingNumber();
      const totalAmount = pricing.grandTotal;
      const advancePaid = paymentMode ? totalAmount : 0; // If paid explicitly, record full upfront payment

      // 4. Generate automated FolioCharges based on GST
      const folioChargesData: any[] = [];
      const isInterState = false; 

      if (durationUnit === 'days') {
        // Daily charges for short stays
        for (const night of pricing.nightlyRates) {
          folioChargesData.push({
            tenantId: req.tenantId!,
            chargeDate: new Date(night.date),
            category: 'room',
            description: `Walk-in Room charge - ${night.date}`,
            sacCode: '996311',
            quantity: 1,
            unitPrice: night.rate,
            totalPrice: night.rate,
            gstRate: night.gstAmount > 0 && night.rate > 0 ? Math.round((night.gstAmount / night.rate) * 100) : 0,
            cgst: isInterState ? 0 : night.gstAmount / 2,
            sgst: isInterState ? 0 : night.gstAmount / 2,
            igst: isInterState ? night.gstAmount : 0,
            isAutoGenerated: true,
          });
        }
      } else {
        // Monthly charges for long stays (PG)
        // Split total across months
        const monthlyRate = Math.floor(pricing.totalAmount / durationValue);
        const monthlyGst = Math.floor(pricing.totalGst / durationValue);
        
        for (let i = 0; i < durationValue; i++) {
          const chargeDate = new Date(checkInDate);
          chargeDate.setMonth(chargeDate.getMonth() + i);
          
          folioChargesData.push({
            tenantId: req.tenantId!,
            chargeDate,
            category: 'room',
            description: `Monthly Walk-in charge - Month ${i + 1}`,
            sacCode: '996311', // Still Hospitality/Accomodation
            quantity: 1,
            unitPrice: monthlyRate,
            totalPrice: monthlyRate,
            gstRate: monthlyGst > 0 ? Math.round((monthlyGst / monthlyRate) * 100) : 0,
            cgst: isInterState ? 0 : monthlyGst / 2,
            sgst: isInterState ? 0 : monthlyGst / 2,
            igst: isInterState ? monthlyGst : 0,
            isAutoGenerated: true,
          });
        }
      }

      // If they paid right now, add GuestPayment
      const guestPaymentsData: any[] = [];
      if (paymentMode) {
        guestPaymentsData.push({
          tenantId: req.tenantId!,
          amount: totalAmount,
          method: paymentMode,
          status: 'completed',
          receiptNumber: `WALKIN-${bookingNumber}`
        });
      }

      // 5. Build the massive Transaction block
      const booking = await prisma.booking.create({
        data: {
          tenantId: req.tenantId!,
          bookingNumber,
          guestProfileId: guestProfile.id,
          guestName,
          guestPhone,
          source: 'walkin',
          checkInDate,
          checkOutDate,
          numAdults: 1,
          numChildren: 0,
          numRooms: 1,
          status: 'checked_in', // Check in immediately!
          totalAmount,
          advancePaid,
          balanceDue: totalAmount - advancePaid,
          createdBy: req.userId,
          bookingRooms: { 
            create: [{
              tenantId: req.tenantId!,
              roomId: room.id,
              roomTypeId: room.roomTypeId,
              ratePerNight: pricing.nightlyRates.length > 0 ? pricing.nightlyRates[0].rate : 0,
              extraBeds: 0,
              extraBedCharge: 0,
            }] 
          },
          bookingGuests: { create: [{ tenantId: req.tenantId!, fullName: guestName }] },
          folioCharges: { create: folioChargesData },
          guestPayments: { create: guestPaymentsData },
        },
        include: { bookingRooms: true, folioCharges: true, guestPayments: true },
      });

      // Update room status
      await prisma.room.update({
        where: { id: room.id },
        data: { status: 'occupied' }
      });

      await logAudit(req.tenantId!, req.userId, 'CREATE', 'booking', booking.id, { bookingNumber, type: 'walkin', paymentMode }, req.ip || undefined);

      return { booking, status: 201 };
    });

    if ('error' in result) {
      res.status(result.status).json({ success: false, error: result.error });
      return;
    }

    res.status(result.status || 200).json({ success: true, booking: result.booking });
  } catch (err) {
    console.error('[WALK-IN BOOKING ERROR]', err);
    res.status(500).json({ success: false, error: err instanceof Error ? err.message : String(err) });
  }
});
